apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joue-zero/devops-platform
      targetRevision: HEAD
      path: helm/app
      helm:
        valueFiles:
          - $values/environments/prod/values.yaml
    - repoURL: https://github.com/joue-zero/gitops-config
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
